version: '2'
services:
  gpg-s3-backup:
    image: alphatam/gpg-s3-backup
    environment:
      S3_REGION: ap-east-1
      S3_ACCESS_KEY_ID: xxx
      S3_SECRET_ACCESS_KEY: xxx
      S3_BUCKET: welend-backups
      S3_PREFIX: backup/product/project
      BACKUP_FILE: /gpg-s3-backup/filename.file
      S3_S3V4: 'yes'
